name: Tests

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]


jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version: [ '7.4' ]
                include:
                    - { operating-system: 'ubuntu-latest', php-version: '8.0', dependencies: '--ignore-platform-req=php', ini-values: 'error_reporting=E_ALL & ~E_DEPRECATED' }

        name: PHP ${{ matrix.php-version }}

        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    coverage: pcov
                    tools: composer:v2
                    ini-values: ${{ matrix.ini-values }}

            -   name: Install dependencies
                run: |
                    composer install --no-interaction --prefer-dist --no-progress ${{ matrix.dependencies }}

            -   name: Run tests
                run: |
                    php vendor/bin/phpunit
